### ISSUE TITLE
Support for movemask_epi8 intrinsincs

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/portable-simd#221] opened 2021-12-23 23:45 UTC
Hello,

I was trying to understand how feasible it would be to port https://github.com/cloudflare/sliceslice-rs to std::simd but was not able to find equivalents to movemask_epi8 intrinsincs like:
* https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_movemask_epi8
* https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_movemask_epi8

As you probably already know, those intrinsincs are creating a mask from the most significant bit of each 8-bit element in src and store the result in dst as a plain integer.

The same operation is also available for wasm32 architecture in the form of https://doc.rust-lang.org/core/arch/wasm32/fn.u8x16_bitmask.html and is probably available on aarch64 too.

This is just a proposal but since the biggest lane count exposed right now is 64, all `Mask<u8, LANES>` could have a `to_scalar` method to achieve this?

Sorry if that already exists and I wasn't able to find it :/

**Comment by marmeladema** [comment] 2021-12-24 00:53
I ultimately found `Mask::to_bitmask` in the codebase, so this + `iXX::from_bytes` should work however, I am unable to call the said `Mask::to_bitmask` even with `generic_const_exprs` feature enabled.

**Comment by thomcc** [comment] 2021-12-24 00:56
I think this is a dupe of https://github.com/rust-lang/portable-simd/issues/204

**Comment by marmeladema** [comment] 2021-12-24 01:07
I thought at first too but the to_bitmask method is not the same as requested here. I don't want an array of u8, I need an integer where each *bit* is made from the msb of each u8 from that array.

**Comment by calebzulawski** [comment] 2021-12-24 04:34
In that function, each bit of each u8 represents a lane--if you want an integer, you can cast it.

**Comment by workingjubilee** [comment] 2021-12-24 06:26
It is not necessarily intended that the 64 lane limit is an actually permanent limitation, nor is it obvious that e.g. 64 or 128 bits is the desirable stopping point, because it is preferable to have a design with "room to grow", especially as creative ISA designs for highly parallel hardware can create almost arbitrarily large vectors. We would _like_ to return generic-length integers instead, but those don't exist in Rust (yet?), so an array it is for now.

**Comment by marmeladema** [comment] 2021-12-24 09:35
Ok thank you for your answer ! Sorry I misunderstood how `to_bitmask` worked.

So in order to use it, I just need to wait for #204 to be fixed?

**Comment by thomcc** [comment] 2021-12-24 18:10
Yes, unfortunately there's not really an alternative.

**Comment by workingjubilee** [comment] 2021-12-24 20:51
> Ok thank you for your answer ! Sorry I misunderstood how `to_bitmask` worked.
> 
> So in order to use it, I just need to wait for #204 to be fixed?

No need to apologize at all, if there is any confusion on the part of users as to what a function is doing then we clearly need to at least take that into account.

I am guessing you thought the length of the byte array was something like "1 per lane" or something like that?

**Closed** 2022-03-02 18:05 UTC
Labels: C-feature-request
